import pandas as pd
import time

current_time = time.strftime('%H:%M:%S')

log_file_reading_interval = 1       # File reading interval (sec)

# +------------------------------------------------------------------+
# FILE TRANSMIT PATHS
# +------------------------------------------------------------------+

mt5_account_number = 515    # LAST 3 DIGITS OF MT5 ACCOUNT. MUST BE CHANGED BEFORE BUILDING EXE

# MT5 directory with OHLC log file (logging on active timeframe):
mt5_logging_file_path = (
    f'C:/Users/Liikurserv/AppData/Roaming/MetaQuotes/Terminal/'
    f'09FF355D73768D9CE6BDD4EE575EAB09/MQL5/Files/'    # HASH FOLDER MUST BE CHANGED BEFORE EXE BUILD
    f'OHLCVData_{mt5_account_number}.csv'
)

# File with signal generated by Python script
buy_sell_signals_for_mt5_filepath = (
     f'C:/Users/Liikurserv/AppData/Roaming/MetaQuotes/Terminal/'
     f'09FF355D73768D9CE6BDD4EE575EAB09/MQL5/Files/'    # HASH FOLDER MUST BE CHANGED BEFORE EXE BUILD
     f'buy_sell_signals_from_python_level.txt'
     )


def get_dataframe_from_file():
    log_df = pd.read_csv(mt5_logging_file_path, sep=';', encoding='utf-16', engine='python')
    new_column_names = ['Ticker', 'Timeframe', 'Datetime', 'Open', 'High', 'Low', 'Close', 'Volume']
    log_df.columns = new_column_names
    log_df['Datetime'] = pd.to_datetime(log_df['Datetime'])
    log_df.set_index('Datetime', inplace=True)
    log_df['Date'] = log_df.index.date
    log_df['Time'] = log_df.index.time
    dataframe_from_log = log_df.loc[:, ['Ticker', 'Date', 'Time', 'Open', 'High', 'Low', 'Close']]
    print(dataframe_from_log)

    return dataframe_from_log






